language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - "python setup.py develop"
  - "pip install nose six pylint pyforge --use-mirrors"
# command to run tests, e.g. python setup.py test
script: python travis_build.py
