language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - "sudo python setup.py develop"
  - "sudo pip install nose"
  - "sudo pip install pylint"
# command to run tests, e.g. python setup.py test
script: nosetests -w tests && epylint shakedown
