language: python
dist: xenial
sudo: false
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"

env:
  - TRAVIS_PYLINT=false
  - TRAVIS_DOCS=false

matrix:
  include:
    - python: "3.6"
      env:
        - TRAVIS_DOCS=true
        - TRAVIS_PYTLINT=true
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
      script: 
        - python -m virtualenv .env
        - .env/Scripts/pip.exe install -e .[testing,doc]
        - .env/Scripts/py.test.exe --cov=slash --cov-report=html tests
  allow_failures:
    - os: windows

# command to run tests, e.g. python setup.py test
install: 
  - pip install virtualenv
  - pip install codecov
script: 
  - make env
  - if [[ $TRAVIS_PYLINT != 'true' ]]; then make test; else make pylint; fi
  - if [[ $TRAVIS_DOCS == 'true' ]]; then make doc; fi
after_success:
  - codecov
after_failure:
- .env/bin/pip freeze

branches:
  except:
    - trying.tmp
    - staging.tmp


deploy:
  - provider: pypi
    user: vmalloc
    password:
      secure: EBE30QsQvwodsakJRtXvmeah0KRQoMpHQSfSACjE0FviWU6eHhgE7nSzxrTSwetmLaB/+hexkys8ULsE4Dxwgvd8aXJ5T6+GnhFkWLgaTl8Q39g/cnLqnVj+OCS95XlyFcWyBLsdyPY+tAc34YpYRfjuWgXup5UNc7Ze2KQ7wqk=
    on:
      tags: true
      repo: getslash/slash
      python: "3.6"
      condition: $TRAVIS_PYLINT = 'false'
