language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

env:
  - TRAVIS_PYLINT=false

matrix:
  include:
    - python: "3.6"
      env: TRAVIS_PYLINT=true

# command to run tests, e.g. python setup.py test
install: 
  - pip install virtualenv
  - pip install codecov
script: 
  - make env
  - if [[ $TRAVIS_PYLINT != 'true' ]]; then make test; else make pylint; fi
after_success:
  - codecov
after_failure:
- .env/bin/pip freeze

deploy:
  - provider: pypi
    user: vmalloc
    password:
      secure: EBE30QsQvwodsakJRtXvmeah0KRQoMpHQSfSACjE0FviWU6eHhgE7nSzxrTSwetmLaB/+hexkys8ULsE4Dxwgvd8aXJ5T6+GnhFkWLgaTl8Q39g/cnLqnVj+OCS95XlyFcWyBLsdyPY+tAc34YpYRfjuWgXup5UNc7Ze2KQ7wqk=
    on:
      tags: true
      repo: getslash/slash
      python: "3.6"
      condition: $TRAVIS_PYLINT=false
